permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 孙卫亮
  email: sun_weiliang@126.com
  link: http://sunweiliang.github.io
  github: http://github.com/sunweiliang

# 站点信息
title: 孙卫亮的博客
description: My personal note-blog.
url: http://sunweiliang.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/gavatar.jpg
favicon: /public/img/favicon.ico

# google analytics 设置
ga:
  id: UA-55089304-1 
  url: http://blog.jimmylv.info

# disqus 设置
disqus:
  shortname: gotoshare

# 主题设置，自动激活某个标签
active: 编程1

# 首页除了最新文章外显示分类
cates: 
  - React1
  - 摄影1

# 中文本地化
locals:
  tags: 标签1
  about: 关于1
  newest: 最新文章1
  archive: 归档1

gems:
  - jekyll-sitemap
  - jekyll-paginate

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
