name: GH Pages CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"

jobs:
  build-deploy:
    runs-on: ubuntu-16.04

    steps:
      - name: Run Backup
        run: |
          cd /tmp
          git clone -q --depth=1 --branch=master https://github.com/JimmyLv/jekyll-blog.git jekyll-blog
          cd $_
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get cached gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build and deploy
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
