name: GH Pages CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"

jobs:
  build-deploy:
    runs-on: ubuntu-16.04

    steps:
      - name: Clone Github Repo Action
        # You may pin to the exact commit or the version.
        # uses: GuillaumeFalourd/clone-github-repo-action@d667f8c39e6ac1dd5309ad51b0020657c7a1a296
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
          # Repository Owner
          owner: JimmyLv
          # Repository name
          repository: jekyll-blog
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Move Files
        uses: crykn/copy_folder_to_another_repo_action@v1.0.6
        with:
          # Source folder from the origin directory
          source_folder: jimmylv.github.io
          # Directory to push the folder contents to
          destination_folder: jekyll-blog/_posts
          
      - name: Get cached gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build and deploy
        uses: helaili/jekyll-action@v2
        with:
          jekyll_src: 'jekyll-blog'
          token: ${{ secrets.GITHUB_TOKEN }}
